#!/bin/sh

echo "https://dl-cdn.alpinelinux.org/alpine/v3.18/main" >> /etc/apk/repositories;
echo "https://dl-cdn.alpinelinux.org/alpine/v3.18/community" >> /etc/apk/repositories;

apk update && apk upgrade --available && sync;

#if ! command -v curl >/dev/null 2>&1; then apk add curl; fi;
#if ! command -v git >/dev/null 2>&1; then apk add git; fi;
if ! command -v node >/dev/null 2>&1; then apk add nodejs; fi;
#if ! command -v nvim >/dev/null 2>&1; then apk add neovim; fi;
if ! command -v ssh >/dev/null 2>&1; then apk add openssh; fi;
if ! command -v vifm >/dev/null 2>&1; then apk add vifm; fi;
if ! command -v vim >/dev/null 2>&1; then apk add vim; fi;
#if ! command -v wget >/dev/null 2>&1; then apk add wget; fi;
